library(shiny)
library(dplyr)
library(plotly)
library(ggplot2)
library(stringr)
library(tidyverse)
library(lubridate)
library(shinyWidgets)
library(shinydashboard)
library(formattable)
library(rsconnect)
library(maps)
library(usdata)
library("ggthemes")
library("scales")
library("mapproj")

source("app_ui.R")
source("app_server.R")

shinyApp(ui = ui, server = server)
